<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('cities')->truncate();
        DB::table('cities')->insert($this->data());
    }

    private function data(): array
    {
        return [
            // ── ACEH ──────────────────────────────────────────────────
            ['name'=>'Banda Aceh',       'province'=>'Aceh','type'=>'Kota',       'lat'=>5.5483,   'lng'=>95.3238],
            ['name'=>'Sabang',           'province'=>'Aceh','type'=>'Kota',       'lat'=>5.8935,   'lng'=>95.3191],
            ['name'=>'Langsa',           'province'=>'Aceh','type'=>'Kota',       'lat'=>4.4683,   'lng'=>97.9681],
            ['name'=>'Lhokseumawe',      'province'=>'Aceh','type'=>'Kota',       'lat'=>5.1801,   'lng'=>97.1500],
            ['name'=>'Subulussalam',     'province'=>'Aceh','type'=>'Kota',       'lat'=>2.6464,   'lng'=>98.0039],
            ['name'=>'Aceh Besar',       'province'=>'Aceh','type'=>'Kabupaten',  'lat'=>5.4752,   'lng'=>95.5311],
            ['name'=>'Aceh Barat',       'province'=>'Aceh','type'=>'Kabupaten',  'lat'=>4.0961,   'lng'=>96.2837],
            ['name'=>'Aceh Selatan',     'province'=>'Aceh','type'=>'Kabupaten',  'lat'=>3.0768,   'lng'=>97.3747],
            ['name'=>'Aceh Singkil',     'province'=>'Aceh','type'=>'Kabupaten',  'lat'=>2.2772,   'lng'=>97.8046],
            ['name'=>'Aceh Tengah',      'province'=>'Aceh','type'=>'Kabupaten',  'lat'=>4.6278,   'lng'=>96.8469],
            ['name'=>'Aceh Tenggara',    'province'=>'Aceh','type'=>'Kabupaten',  'lat'=>3.6826,   'lng'=>97.7534],
            ['name'=>'Aceh Timur',       'province'=>'Aceh','type'=>'Kabupaten',  'lat'=>4.5798,   'lng'=>97.8697],
            ['name'=>'Aceh Utara',       'province'=>'Aceh','type'=>'Kabupaten',  'lat'=>5.0641,   'lng'=>97.0984],
            ['name'=>'Bener Meriah',     'province'=>'Aceh','type'=>'Kabupaten',  'lat'=>4.7296,   'lng'=>96.9136],
            ['name'=>'Bireuen',          'province'=>'Aceh','type'=>'Kabupaten',  'lat'=>5.2010,   'lng'=>96.7030],
            ['name'=>'Gayo Lues',        'province'=>'Aceh','type'=>'Kabupaten',  'lat'=>3.8510,   'lng'=>97.4540],
            ['name'=>'Nagan Raya',       'province'=>'Aceh','type'=>'Kabupaten',  'lat'=>4.0100,   'lng'=>96.3770],
            ['name'=>'Pidie',            'province'=>'Aceh','type'=>'Kabupaten',  'lat'=>4.9640,   'lng'=>96.2840],
            ['name'=>'Pidie Jaya',       'province'=>'Aceh','type'=>'Kabupaten',  'lat'=>5.1360,   'lng'=>96.0770],
            ['name'=>'Simeulue',         'province'=>'Aceh','type'=>'Kabupaten',  'lat'=>2.6390,   'lng'=>96.1000],
            ['name'=>'Aceh Barat Daya',  'province'=>'Aceh','type'=>'Kabupaten',  'lat'=>3.4290,   'lng'=>96.8550],
            ['name'=>'Aceh Jaya',        'province'=>'Aceh','type'=>'Kabupaten',  'lat'=>4.5590,   'lng'=>95.6580],

            // ── SUMATERA UTARA ────────────────────────────────────────
            ['name'=>'Medan',            'province'=>'Sumatera Utara','type'=>'Kota',      'lat'=>3.5952,  'lng'=>98.6722],
            ['name'=>'Binjai',           'province'=>'Sumatera Utara','type'=>'Kota',      'lat'=>3.6002,  'lng'=>98.4855],
            ['name'=>'Gunungsitoli',     'province'=>'Sumatera Utara','type'=>'Kota',      'lat'=>1.2883,  'lng'=>97.6137],
            ['name'=>'Padangsidempuan', 'province'=>'Sumatera Utara','type'=>'Kota',      'lat'=>1.3787,  'lng'=>99.2726],
            ['name'=>'Pematangsiantar',  'province'=>'Sumatera Utara','type'=>'Kota',      'lat'=>2.9595,  'lng'=>99.0687],
            ['name'=>'Sibolga',          'province'=>'Sumatera Utara','type'=>'Kota',      'lat'=>1.7427,  'lng'=>98.7792],
            ['name'=>'Tanjungbalai',     'province'=>'Sumatera Utara','type'=>'Kota',      'lat'=>2.9668,  'lng'=>99.8007],
            ['name'=>'Tebing Tinggi',    'province'=>'Sumatera Utara','type'=>'Kota',      'lat'=>3.3281,  'lng'=>99.1624],
            ['name'=>'Asahan',           'province'=>'Sumatera Utara','type'=>'Kabupaten', 'lat'=>2.9935,  'lng'=>99.5775],
            ['name'=>'Batu Bara',        'province'=>'Sumatera Utara','type'=>'Kabupaten', 'lat'=>3.0650,  'lng'=>99.4710],
            ['name'=>'Dairi',            'province'=>'Sumatera Utara','type'=>'Kabupaten', 'lat'=>2.7764,  'lng'=>98.3228],
            ['name'=>'Deli Serdang',     'province'=>'Sumatera Utara','type'=>'Kabupaten', 'lat'=>3.4567,  'lng'=>98.7879],
            ['name'=>'Humbang Hasundutan','province'=>'Sumatera Utara','type'=>'Kabupaten','lat'=>2.2790, 'lng'=>98.5760],
            ['name'=>'Karo',             'province'=>'Sumatera Utara','type'=>'Kabupaten', 'lat'=>3.0881,  'lng'=>98.4838],
            ['name'=>'Labuhanbatu',      'province'=>'Sumatera Utara','type'=>'Kabupaten', 'lat'=>2.1153,  'lng'=>100.0723],
            ['name'=>'Labuhanbatu Selatan','province'=>'Sumatera Utara','type'=>'Kabupaten','lat'=>1.8530,'lng'=>99.9920],
            ['name'=>'Labuhanbatu Utara','province'=>'Sumatera Utara','type'=>'Kabupaten', 'lat'=>2.4070,  'lng'=>100.0090],
            ['name'=>'Langkat',          'province'=>'Sumatera Utara','type'=>'Kabupaten', 'lat'=>3.8700,  'lng'=>98.2340],
            ['name'=>'Mandailing Natal', 'province'=>'Sumatera Utara','type'=>'Kabupaten', 'lat'=>0.8428,  'lng'=>99.3548],
            ['name'=>'Nias',             'province'=>'Sumatera Utara','type'=>'Kabupaten', 'lat'=>1.0818,  'lng'=>97.7534],
            ['name'=>'Nias Barat',       'province'=>'Sumatera Utara','type'=>'Kabupaten', 'lat'=>0.9150,  'lng'=>97.5310],
            ['name'=>'Nias Selatan',     'province'=>'Sumatera Utara','type'=>'Kabupaten', 'lat'=>0.2778,  'lng'=>97.7833],
            ['name'=>'Nias Utara',       'province'=>'Sumatera Utara','type'=>'Kabupaten', 'lat'=>1.5060,  'lng'=>97.5680],
            ['name'=>'Padang Lawas',     'province'=>'Sumatera Utara','type'=>'Kabupaten', 'lat'=>1.4530,  'lng'=>99.7270],
            ['name'=>'Padang Lawas Utara','province'=>'Sumatera Utara','type'=>'Kabupaten','lat'=>1.7280,  'lng'=>99.5780],
            ['name'=>'Pakpak Bharat',    'province'=>'Sumatera Utara','type'=>'Kabupaten', 'lat'=>2.4330,  'lng'=>98.1580],
            ['name'=>'Samosir',          'province'=>'Sumatera Utara','type'=>'Kabupaten', 'lat'=>2.5980,  'lng'=>98.8260],
            ['name'=>'Serdang Bedagai',  'province'=>'Sumatera Utara','type'=>'Kabupaten', 'lat'=>3.3720,  'lng'=>99.0140],
            ['name'=>'Simalungun',       'province'=>'Sumatera Utara','type'=>'Kabupaten', 'lat'=>3.0040,  'lng'=>99.2580],
            ['name'=>'Tapanuli Selatan', 'province'=>'Sumatera Utara','type'=>'Kabupaten', 'lat'=>1.6650,  'lng'=>99.2360],
            ['name'=>'Tapanuli Tengah',  'province'=>'Sumatera Utara','type'=>'Kabupaten', 'lat'=>1.9770,  'lng'=>98.7960],
            ['name'=>'Tapanuli Utara',   'province'=>'Sumatera Utara','type'=>'Kabupaten', 'lat'=>2.2380,  'lng'=>99.0790],
            ['name'=>'Toba',             'province'=>'Sumatera Utara','type'=>'Kabupaten', 'lat'=>2.3530,  'lng'=>99.1590],

            // ── SUMATERA BARAT ────────────────────────────────────────
            ['name'=>'Padang',           'province'=>'Sumatera Barat','type'=>'Kota',      'lat'=>-0.9492, 'lng'=>100.3543],
            ['name'=>'Bukittinggi',      'province'=>'Sumatera Barat','type'=>'Kota',      'lat'=>-0.3054, 'lng'=>100.3694],
            ['name'=>'Padangpanjang',    'province'=>'Sumatera Barat','type'=>'Kota',      'lat'=>-0.4628, 'lng'=>100.4078],
            ['name'=>'Pariaman',         'province'=>'Sumatera Barat','type'=>'Kota',      'lat'=>-0.6230, 'lng'=>100.1180],
            ['name'=>'Payakumbuh',       'province'=>'Sumatera Barat','type'=>'Kota',      'lat'=>-0.2269, 'lng'=>100.6274],
            ['name'=>'Sawahlunto',       'province'=>'Sumatera Barat','type'=>'Kota',      'lat'=>-0.6843, 'lng'=>100.7776],
            ['name'=>'Solok',            'province'=>'Sumatera Barat','type'=>'Kota',      'lat'=>-0.7965, 'lng'=>100.6570],
            ['name'=>'Agam',             'province'=>'Sumatera Barat','type'=>'Kabupaten', 'lat'=>-0.2380, 'lng'=>100.0500],
            ['name'=>'Dharmasraya',      'province'=>'Sumatera Barat','type'=>'Kabupaten', 'lat'=>-1.2040, 'lng'=>101.4500],
            ['name'=>'Kepulauan Mentawai','province'=>'Sumatera Barat','type'=>'Kabupaten','lat'=>-2.1869,'lng'=>99.5500],
            ['name'=>'Lima Puluh Kota',  'province'=>'Sumatera Barat','type'=>'Kabupaten', 'lat'=>-0.3530, 'lng'=>100.6720],
            ['name'=>'Padang Pariaman',  'province'=>'Sumatera Barat','type'=>'Kabupaten', 'lat'=>-0.4210, 'lng'=>100.1670],
            ['name'=>'Pasaman',          'province'=>'Sumatera Barat','type'=>'Kabupaten', 'lat'=>0.2790,  'lng'=>99.9210],
            ['name'=>'Pasaman Barat',    'province'=>'Sumatera Barat','type'=>'Kabupaten', 'lat'=>0.0740,  'lng'=>99.6470],
            ['name'=>'Pesisir Selatan',  'province'=>'Sumatera Barat','type'=>'Kabupaten', 'lat'=>-1.8590, 'lng'=>100.6800],
            ['name'=>'Sijunjung',        'province'=>'Sumatera Barat','type'=>'Kabupaten', 'lat'=>-0.6960, 'lng'=>100.9680],
            ['name'=>'Solok Selatan',    'province'=>'Sumatera Barat','type'=>'Kabupaten', 'lat'=>-1.4730, 'lng'=>101.1790],
            ['name'=>'Tanah Datar',      'province'=>'Sumatera Barat','type'=>'Kabupaten', 'lat'=>-0.4620, 'lng'=>100.5070],

            // ── RIAU ──────────────────────────────────────────────────
            ['name'=>'Pekanbaru',        'province'=>'Riau','type'=>'Kota',       'lat'=>0.5335,  'lng'=>101.4508],
            ['name'=>'Dumai',            'province'=>'Riau','type'=>'Kota',       'lat'=>1.6724,  'lng'=>101.4472],
            ['name'=>'Bengkalis',        'province'=>'Riau','type'=>'Kabupaten',  'lat'=>1.4845,  'lng'=>102.1085],
            ['name'=>'Indragiri Hilir',  'province'=>'Riau','type'=>'Kabupaten',  'lat'=>-0.4830, 'lng'=>103.1730],
            ['name'=>'Indragiri Hulu',   'province'=>'Riau','type'=>'Kabupaten',  'lat'=>0.2750,  'lng'=>102.4450],
            ['name'=>'Kampar',           'province'=>'Riau','type'=>'Kabupaten',  'lat'=>0.3620,  'lng'=>101.0200],
            ['name'=>'Kepulauan Meranti','province'=>'Riau','type'=>'Kabupaten',  'lat'=>1.1900,  'lng'=>102.7220],
            ['name'=>'Kuantan Singingi', 'province'=>'Riau','type'=>'Kabupaten',  'lat'=>-0.3550, 'lng'=>101.4690],
            ['name'=>'Pelalawan',        'province'=>'Riau','type'=>'Kabupaten',  'lat'=>0.0010,  'lng'=>102.1130],
            ['name'=>'Rokan Hilir',      'province'=>'Riau','type'=>'Kabupaten',  'lat'=>2.1520,  'lng'=>100.9360],
            ['name'=>'Rokan Hulu',       'province'=>'Riau','type'=>'Kabupaten',  'lat'=>0.9090,  'lng'=>100.3730],
            ['name'=>'Siak',             'province'=>'Riau','type'=>'Kabupaten',  'lat'=>1.2470,  'lng'=>102.0060],

            // ── KEPULAUAN RIAU ────────────────────────────────────────
            ['name'=>'Batam',            'province'=>'Kepulauan Riau','type'=>'Kota',      'lat'=>1.1301,  'lng'=>104.0529],
            ['name'=>'Tanjungpinang',    'province'=>'Kepulauan Riau','type'=>'Kota',      'lat'=>0.9188,  'lng'=>104.4684],
            ['name'=>'Bintan',           'province'=>'Kepulauan Riau','type'=>'Kabupaten', 'lat'=>1.0450,  'lng'=>104.5290],
            ['name'=>'Karimun',          'province'=>'Kepulauan Riau','type'=>'Kabupaten', 'lat'=>1.0350,  'lng'=>103.4430],
            ['name'=>'Kepulauan Anambas','province'=>'Kepulauan Riau','type'=>'Kabupaten', 'lat'=>3.3470,  'lng'=>106.2430],
            ['name'=>'Lingga',           'province'=>'Kepulauan Riau','type'=>'Kabupaten', 'lat'=>0.2140,  'lng'=>104.6390],
            ['name'=>'Natuna',           'province'=>'Kepulauan Riau','type'=>'Kabupaten', 'lat'=>3.9890,  'lng'=>108.3480],

            // ── JAMBI ─────────────────────────────────────────────────
            ['name'=>'Jambi',            'province'=>'Jambi','type'=>'Kota',       'lat'=>-1.6101, 'lng'=>103.6131],
            ['name'=>'Sungai Penuh',     'province'=>'Jambi','type'=>'Kota',       'lat'=>-2.0620, 'lng'=>101.3970],
            ['name'=>'Batanghari',       'province'=>'Jambi','type'=>'Kabupaten',  'lat'=>-1.8260, 'lng'=>103.0920],
            ['name'=>'Bungo',            'province'=>'Jambi','type'=>'Kabupaten',  'lat'=>-1.4490, 'lng'=>102.1210],
            ['name'=>'Kerinci',          'province'=>'Jambi','type'=>'Kabupaten',  'lat'=>-2.0810, 'lng'=>101.4380],
            ['name'=>'Merangin',         'province'=>'Jambi','type'=>'Kabupaten',  'lat'=>-2.1220, 'lng'=>102.3480],
            ['name'=>'Muaro Jambi',      'province'=>'Jambi','type'=>'Kabupaten',  'lat'=>-1.5990, 'lng'=>103.7960],
            ['name'=>'Sarolangun',       'province'=>'Jambi','type'=>'Kabupaten',  'lat'=>-2.2820, 'lng'=>102.6740],
            ['name'=>'Tanjung Jabung Barat','province'=>'Jambi','type'=>'Kabupaten','lat'=>-1.2060,'lng'=>103.0920],
            ['name'=>'Tanjung Jabung Timur','province'=>'Jambi','type'=>'Kabupaten','lat'=>-1.1110,'lng'=>104.0850],
            ['name'=>'Tebo',             'province'=>'Jambi','type'=>'Kabupaten',  'lat'=>-1.4940, 'lng'=>102.4880],

            // ── SUMATERA SELATAN ──────────────────────────────────────
            ['name'=>'Palembang',        'province'=>'Sumatera Selatan','type'=>'Kota',      'lat'=>-2.9761, 'lng'=>104.7754],
            ['name'=>'Lubuklinggau',     'province'=>'Sumatera Selatan','type'=>'Kota',      'lat'=>-3.2956, 'lng'=>102.8614],
            ['name'=>'Pagar Alam',       'province'=>'Sumatera Selatan','type'=>'Kota',      'lat'=>-4.0220, 'lng'=>103.2510],
            ['name'=>'Prabumulih',       'province'=>'Sumatera Selatan','type'=>'Kota',      'lat'=>-3.4310, 'lng'=>104.2340],
            ['name'=>'Banyuasin',        'province'=>'Sumatera Selatan','type'=>'Kabupaten', 'lat'=>-2.5480, 'lng'=>104.8090],
            ['name'=>'Empat Lawang',     'province'=>'Sumatera Selatan','type'=>'Kabupaten', 'lat'=>-3.5430, 'lng'=>103.2980],
            ['name'=>'Lahat',            'province'=>'Sumatera Selatan','type'=>'Kabupaten', 'lat'=>-3.7890, 'lng'=>103.5310],
            ['name'=>'Muara Enim',       'province'=>'Sumatera Selatan','type'=>'Kabupaten', 'lat'=>-3.6710, 'lng'=>103.7460],
            ['name'=>'Musi Banyuasin',   'province'=>'Sumatera Selatan','type'=>'Kabupaten', 'lat'=>-2.5920, 'lng'=>103.9750],
            ['name'=>'Musi Rawas',       'province'=>'Sumatera Selatan','type'=>'Kabupaten', 'lat'=>-3.0580, 'lng'=>102.8810],
            ['name'=>'Musi Rawas Utara', 'province'=>'Sumatera Selatan','type'=>'Kabupaten', 'lat'=>-2.7810, 'lng'=>103.1240],
            ['name'=>'Ogan Ilir',        'province'=>'Sumatera Selatan','type'=>'Kabupaten', 'lat'=>-3.2280, 'lng'=>104.6490],
            ['name'=>'Ogan Komering Ilir','province'=>'Sumatera Selatan','type'=>'Kabupaten','lat'=>-3.5210,'lng'=>105.3630],
            ['name'=>'Ogan Komering Ulu','province'=>'Sumatera Selatan','type'=>'Kabupaten', 'lat'=>-4.0180, 'lng'=>104.1570],
            ['name'=>'OKU Selatan',      'province'=>'Sumatera Selatan','type'=>'Kabupaten', 'lat'=>-4.5490, 'lng'=>103.9040],
            ['name'=>'OKU Timur',        'province'=>'Sumatera Selatan','type'=>'Kabupaten', 'lat'=>-4.1370, 'lng'=>104.5580],
            ['name'=>'PALI',             'province'=>'Sumatera Selatan','type'=>'Kabupaten', 'lat'=>-3.1800, 'lng'=>103.8110],

            // ── BENGKULU ──────────────────────────────────────────────
            ['name'=>'Bengkulu',         'province'=>'Bengkulu','type'=>'Kota',       'lat'=>-3.7928, 'lng'=>102.2608],
            ['name'=>'Bengkulu Selatan', 'province'=>'Bengkulu','type'=>'Kabupaten',  'lat'=>-4.4140, 'lng'=>102.8140],
            ['name'=>'Bengkulu Tengah',  'province'=>'Bengkulu','type'=>'Kabupaten',  'lat'=>-3.7250, 'lng'=>102.3710],
            ['name'=>'Bengkulu Utara',   'province'=>'Bengkulu','type'=>'Kabupaten',  'lat'=>-3.0820, 'lng'=>101.9210],
            ['name'=>'Kaur',             'province'=>'Bengkulu','type'=>'Kabupaten',  'lat'=>-4.7890, 'lng'=>103.3260],
            ['name'=>'Kepahiang',        'province'=>'Bengkulu','type'=>'Kabupaten',  'lat'=>-3.6510, 'lng'=>102.5950],
            ['name'=>'Lebong',           'province'=>'Bengkulu','type'=>'Kabupaten',  'lat'=>-3.1610, 'lng'=>102.3590],
            ['name'=>'Mukomuko',         'province'=>'Bengkulu','type'=>'Kabupaten',  'lat'=>-2.5210, 'lng'=>101.1220],
            ['name'=>'Rejang Lebong',    'province'=>'Bengkulu','type'=>'Kabupaten',  'lat'=>-3.4630, 'lng'=>102.5510],
            ['name'=>'Seluma',           'province'=>'Bengkulu','type'=>'Kabupaten',  'lat'=>-4.0760, 'lng'=>102.5440],

            // ── LAMPUNG ───────────────────────────────────────────────
            ['name'=>'Bandar Lampung',   'province'=>'Lampung','type'=>'Kota',       'lat'=>-5.4297, 'lng'=>105.2608],
            ['name'=>'Metro',            'province'=>'Lampung','type'=>'Kota',       'lat'=>-5.1130, 'lng'=>105.3060],
            ['name'=>'Lampung Barat',    'province'=>'Lampung','type'=>'Kabupaten',  'lat'=>-4.9680, 'lng'=>104.2250],
            ['name'=>'Lampung Selatan',  'province'=>'Lampung','type'=>'Kabupaten',  'lat'=>-5.5920, 'lng'=>105.5530],
            ['name'=>'Lampung Tengah',   'province'=>'Lampung','type'=>'Kabupaten',  'lat'=>-4.8970, 'lng'=>105.2250],
            ['name'=>'Lampung Timur',    'province'=>'Lampung','type'=>'Kabupaten',  'lat'=>-5.0680, 'lng'=>105.7120],
            ['name'=>'Lampung Utara',    'province'=>'Lampung','type'=>'Kabupaten',  'lat'=>-4.5310, 'lng'=>104.9020],
            ['name'=>'Mesuji',           'province'=>'Lampung','type'=>'Kabupaten',  'lat'=>-3.8680, 'lng'=>105.3210],
            ['name'=>'Pesawaran',        'province'=>'Lampung','type'=>'Kabupaten',  'lat'=>-5.3840, 'lng'=>105.1810],
            ['name'=>'Pesisir Barat',    'province'=>'Lampung','type'=>'Kabupaten',  'lat'=>-5.0560, 'lng'=>103.9130],
            ['name'=>'Pringsewu',        'province'=>'Lampung','type'=>'Kabupaten',  'lat'=>-5.3580, 'lng'=>104.9740],
            ['name'=>'Tanggamus',        'province'=>'Lampung','type'=>'Kabupaten',  'lat'=>-5.3760, 'lng'=>104.6260],
            ['name'=>'Tulang Bawang',    'province'=>'Lampung','type'=>'Kabupaten',  'lat'=>-4.2490, 'lng'=>105.5090],
            ['name'=>'Tulang Bawang Barat','province'=>'Lampung','type'=>'Kabupaten','lat'=>-4.4180, 'lng'=>105.1520],
            ['name'=>'Way Kanan',        'province'=>'Lampung','type'=>'Kabupaten',  'lat'=>-4.3310, 'lng'=>104.6330],

            // ── BANGKA BELITUNG ───────────────────────────────────────
            ['name'=>'Pangkalpinang',    'province'=>'Bangka Belitung','type'=>'Kota',      'lat'=>-2.1316, 'lng'=>106.1167],
            ['name'=>'Bangka',           'province'=>'Bangka Belitung','type'=>'Kabupaten', 'lat'=>-2.2530, 'lng'=>106.1750],
            ['name'=>'Bangka Barat',     'province'=>'Bangka Belitung','type'=>'Kabupaten', 'lat'=>-1.8670, 'lng'=>105.4870],
            ['name'=>'Bangka Selatan',   'province'=>'Bangka Belitung','type'=>'Kabupaten', 'lat'=>-2.9040, 'lng'=>106.4880],
            ['name'=>'Bangka Tengah',    'province'=>'Bangka Belitung','type'=>'Kabupaten', 'lat'=>-2.4650, 'lng'=>106.3840],
            ['name'=>'Belitung',         'province'=>'Bangka Belitung','type'=>'Kabupaten', 'lat'=>-2.7910, 'lng'=>107.6940],
            ['name'=>'Belitung Timur',   'province'=>'Bangka Belitung','type'=>'Kabupaten', 'lat'=>-2.8640, 'lng'=>108.1680],

            // ── BANTEN ────────────────────────────────────────────────
            ['name'=>'Cilegon',          'province'=>'Banten','type'=>'Kota',       'lat'=>-6.0023, 'lng'=>106.0052],
            ['name'=>'Serang',           'province'=>'Banten','type'=>'Kota',       'lat'=>-6.1201, 'lng'=>106.1503],
            ['name'=>'Tangerang',        'province'=>'Banten','type'=>'Kota',       'lat'=>-6.1784, 'lng'=>106.6319],
            ['name'=>'Tangerang Selatan','province'=>'Banten','type'=>'Kota',       'lat'=>-6.2877, 'lng'=>106.7137],
            ['name'=>'Lebak',            'province'=>'Banten','type'=>'Kabupaten',  'lat'=>-6.5630, 'lng'=>106.2500],
            ['name'=>'Pandeglang',       'province'=>'Banten','type'=>'Kabupaten',  'lat'=>-6.3082, 'lng'=>106.1062],
            ['name'=>'Serang',           'province'=>'Banten','type'=>'Kabupaten',  'lat'=>-6.2110, 'lng'=>106.1540],
            ['name'=>'Tangerang',        'province'=>'Banten','type'=>'Kabupaten',  'lat'=>-6.1660, 'lng'=>106.5620],

            // ── DKI JAKARTA ───────────────────────────────────────────
            ['name'=>'Jakarta Barat',    'province'=>'DKI Jakarta','type'=>'Kota',   'lat'=>-6.1675, 'lng'=>106.7637],
            ['name'=>'Jakarta Pusat',    'province'=>'DKI Jakarta','type'=>'Kota',   'lat'=>-6.1805, 'lng'=>106.8284],
            ['name'=>'Jakarta Selatan',  'province'=>'DKI Jakarta','type'=>'Kota',   'lat'=>-6.2615, 'lng'=>106.8106],
            ['name'=>'Jakarta Timur',    'province'=>'DKI Jakarta','type'=>'Kota',   'lat'=>-6.2250, 'lng'=>106.9004],
            ['name'=>'Jakarta Utara',    'province'=>'DKI Jakarta','type'=>'Kota',   'lat'=>-6.1382, 'lng'=>106.8463],
            ['name'=>'Kepulauan Seribu', 'province'=>'DKI Jakarta','type'=>'Kabupaten','lat'=>-5.6139,'lng'=>106.5697],

            // ── JAWA BARAT ────────────────────────────────────────────
            ['name'=>'Bandung',          'province'=>'Jawa Barat','type'=>'Kota',      'lat'=>-6.9175,  'lng'=>107.6191],
            ['name'=>'Banjar',           'province'=>'Jawa Barat','type'=>'Kota',      'lat'=>-7.3709,  'lng'=>108.5378],
            ['name'=>'Bekasi',           'province'=>'Jawa Barat','type'=>'Kota',      'lat'=>-6.2349,  'lng'=>106.9896],
            ['name'=>'Bogor',            'province'=>'Jawa Barat','type'=>'Kota',      'lat'=>-6.5971,  'lng'=>106.8060],
            ['name'=>'Cimahi',           'province'=>'Jawa Barat','type'=>'Kota',      'lat'=>-6.8713,  'lng'=>107.5420],
            ['name'=>'Cirebon',          'province'=>'Jawa Barat','type'=>'Kota',      'lat'=>-6.7320,  'lng'=>108.5523],
            ['name'=>'Depok',            'province'=>'Jawa Barat','type'=>'Kota',      'lat'=>-6.4025,  'lng'=>106.7942],
            ['name'=>'Sukabumi',         'province'=>'Jawa Barat','type'=>'Kota',      'lat'=>-6.9215,  'lng'=>106.9270],
            ['name'=>'Tasikmalaya',      'province'=>'Jawa Barat','type'=>'Kota',      'lat'=>-7.3274,  'lng'=>108.2207],
            ['name'=>'Bandung',          'province'=>'Jawa Barat','type'=>'Kabupaten', 'lat'=>-7.0416,  'lng'=>107.5778],
            ['name'=>'Bandung Barat',    'province'=>'Jawa Barat','type'=>'Kabupaten', 'lat'=>-6.8430,  'lng'=>107.4530],
            ['name'=>'Bekasi',           'province'=>'Jawa Barat','type'=>'Kabupaten', 'lat'=>-6.3750,  'lng'=>107.1640],
            ['name'=>'Bogor',            'province'=>'Jawa Barat','type'=>'Kabupaten', 'lat'=>-6.5960,  'lng'=>106.8590],
            ['name'=>'Ciamis',           'province'=>'Jawa Barat','type'=>'Kabupaten', 'lat'=>-7.3310,  'lng'=>108.3520],
            ['name'=>'Cianjur',          'province'=>'Jawa Barat','type'=>'Kabupaten', 'lat'=>-6.8210,  'lng'=>107.1390],
            ['name'=>'Cirebon',          'province'=>'Jawa Barat','type'=>'Kabupaten', 'lat'=>-6.7560,  'lng'=>108.4820],
            ['name'=>'Garut',            'province'=>'Jawa Barat','type'=>'Kabupaten', 'lat'=>-7.2130,  'lng'=>107.8960],
            ['name'=>'Indramayu',        'province'=>'Jawa Barat','type'=>'Kabupaten', 'lat'=>-6.3280,  'lng'=>108.3230],
            ['name'=>'Karawang',         'province'=>'Jawa Barat','type'=>'Kabupaten', 'lat'=>-6.3210,  'lng'=>107.3390],
            ['name'=>'Kuningan',         'province'=>'Jawa Barat','type'=>'Kabupaten', 'lat'=>-6.9760,  'lng'=>108.4850],
            ['name'=>'Majalengka',       'province'=>'Jawa Barat','type'=>'Kabupaten', 'lat'=>-6.8360,  'lng'=>108.2270],
            ['name'=>'Pangandaran',      'province'=>'Jawa Barat','type'=>'Kabupaten', 'lat'=>-7.6880,  'lng'=>108.6510],
            ['name'=>'Purwakarta',       'province'=>'Jawa Barat','type'=>'Kabupaten', 'lat'=>-6.5560,  'lng'=>107.4390],
            ['name'=>'Subang',           'province'=>'Jawa Barat','type'=>'Kabupaten', 'lat'=>-6.5720,  'lng'=>107.7610],
            ['name'=>'Sukabumi',         'province'=>'Jawa Barat','type'=>'Kabupaten', 'lat'=>-6.9130,  'lng'=>106.9280],
            ['name'=>'Sumedang',         'province'=>'Jawa Barat','type'=>'Kabupaten', 'lat'=>-6.8570,  'lng'=>107.9220],
            ['name'=>'Tasikmalaya',      'province'=>'Jawa Barat','type'=>'Kabupaten', 'lat'=>-7.3770,  'lng'=>108.1080],

            // ── JAWA TENGAH ───────────────────────────────────────────
            ['name'=>'Magelang',         'province'=>'Jawa Tengah','type'=>'Kota',      'lat'=>-7.4706,  'lng'=>110.2177],
            ['name'=>'Pekalongan',       'province'=>'Jawa Tengah','type'=>'Kota',      'lat'=>-6.8886,  'lng'=>109.6753],
            ['name'=>'Purwokerto',       'province'=>'Jawa Tengah','type'=>'Kota',      'lat'=>-7.4241,  'lng'=>109.2354],
            ['name'=>'Salatiga',         'province'=>'Jawa Tengah','type'=>'Kota',      'lat'=>-7.3310,  'lng'=>110.4920],
            ['name'=>'Semarang',         'province'=>'Jawa Tengah','type'=>'Kota',      'lat'=>-6.9932,  'lng'=>110.4203],
            ['name'=>'Solo',             'province'=>'Jawa Tengah','type'=>'Kota',      'lat'=>-7.5755,  'lng'=>110.8243],
            ['name'=>'Tegal',            'province'=>'Jawa Tengah','type'=>'Kota',      'lat'=>-6.8694,  'lng'=>109.1402],
            ['name'=>'Banjarnegara',     'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-7.3910,  'lng'=>109.6940],
            ['name'=>'Banyumas',         'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-7.5280,  'lng'=>109.2930],
            ['name'=>'Batang',           'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-6.9100,  'lng'=>109.7290],
            ['name'=>'Blora',            'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-6.9620,  'lng'=>111.4140],
            ['name'=>'Boyolali',         'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-7.5320,  'lng'=>110.5990],
            ['name'=>'Brebes',           'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-6.8720,  'lng'=>109.0410],
            ['name'=>'Cilacap',          'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-7.7290,  'lng'=>109.0150],
            ['name'=>'Demak',            'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-6.8940,  'lng'=>110.6330],
            ['name'=>'Grobogan',         'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-7.0560,  'lng'=>110.9230],
            ['name'=>'Jepara',           'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-6.5870,  'lng'=>110.6680],
            ['name'=>'Karanganyar',      'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-7.5970,  'lng'=>111.0270],
            ['name'=>'Kebumen',          'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-7.6680,  'lng'=>109.6530],
            ['name'=>'Kendal',           'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-6.9230,  'lng'=>110.1980],
            ['name'=>'Klaten',           'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-7.7060,  'lng'=>110.6050],
            ['name'=>'Kudus',            'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-6.8050,  'lng'=>110.8370],
            ['name'=>'Magelang',         'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-7.5590,  'lng'=>110.2270],
            ['name'=>'Pati',             'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-6.7540,  'lng'=>111.0370],
            ['name'=>'Pekalongan',       'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-6.9980,  'lng'=>109.6620],
            ['name'=>'Pemalang',         'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-6.8900,  'lng'=>109.3810],
            ['name'=>'Purbalingga',      'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-7.3860,  'lng'=>109.3650],
            ['name'=>'Purworejo',        'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-7.7140,  'lng'=>110.0130],
            ['name'=>'Rembang',          'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-6.7050,  'lng'=>111.3420],
            ['name'=>'Semarang',         'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-7.0580,  'lng'=>110.4290],
            ['name'=>'Sragen',           'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-7.4260,  'lng'=>111.0280],
            ['name'=>'Sukoharjo',        'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-7.6780,  'lng'=>110.8380],
            ['name'=>'Tegal',            'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-6.9800,  'lng'=>109.1420],
            ['name'=>'Temanggung',       'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-7.3190,  'lng'=>110.1680],
            ['name'=>'Wonogiri',         'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-7.8130,  'lng'=>110.9240],
            ['name'=>'Wonosobo',         'province'=>'Jawa Tengah','type'=>'Kabupaten', 'lat'=>-7.3620,  'lng'=>109.9040],

            // ── DI YOGYAKARTA ─────────────────────────────────────────
            ['name'=>'Yogyakarta',       'province'=>'DI Yogyakarta','type'=>'Kota',      'lat'=>-7.7956,  'lng'=>110.3695],
            ['name'=>'Bantul',           'province'=>'DI Yogyakarta','type'=>'Kabupaten', 'lat'=>-7.8884,  'lng'=>110.3290],
            ['name'=>'Gunungkidul',      'province'=>'DI Yogyakarta','type'=>'Kabupaten', 'lat'=>-7.9713,  'lng'=>110.5920],
            ['name'=>'Kulon Progo',      'province'=>'DI Yogyakarta','type'=>'Kabupaten', 'lat'=>-7.8322,  'lng'=>110.1600],
            ['name'=>'Sleman',           'province'=>'DI Yogyakarta','type'=>'Kabupaten', 'lat'=>-7.7168,  'lng'=>110.3560],

            // ── JAWA TIMUR ────────────────────────────────────────────
            ['name'=>'Batu',             'province'=>'Jawa Timur','type'=>'Kota',      'lat'=>-7.8742,  'lng'=>112.5285],
            ['name'=>'Blitar',           'province'=>'Jawa Timur','type'=>'Kota',      'lat'=>-8.0957,  'lng'=>112.1608],
            ['name'=>'Kediri',           'province'=>'Jawa Timur','type'=>'Kota',      'lat'=>-7.8480,  'lng'=>112.0172],
            ['name'=>'Madiun',           'province'=>'Jawa Timur','type'=>'Kota',      'lat'=>-7.6298,  'lng'=>111.5239],
            ['name'=>'Malang',           'province'=>'Jawa Timur','type'=>'Kota',      'lat'=>-7.9797,  'lng'=>112.6304],
            ['name'=>'Mojokerto',        'province'=>'Jawa Timur','type'=>'Kota',      'lat'=>-7.4724,  'lng'=>112.4338],
            ['name'=>'Pasuruan',         'province'=>'Jawa Timur','type'=>'Kota',      'lat'=>-7.6454,  'lng'=>112.9075],
            ['name'=>'Probolinggo',      'province'=>'Jawa Timur','type'=>'Kota',      'lat'=>-7.7543,  'lng'=>113.2159],
            ['name'=>'Surabaya',         'province'=>'Jawa Timur','type'=>'Kota',      'lat'=>-7.2575,  'lng'=>112.7521],
            ['name'=>'Bangkalan',        'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-7.0450,  'lng'=>112.7320],
            ['name'=>'Banyuwangi',       'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-8.2192,  'lng'=>114.3691],
            ['name'=>'Blitar',           'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-8.1000,  'lng'=>112.1670],
            ['name'=>'Bojonegoro',       'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-7.1490,  'lng'=>111.8810],
            ['name'=>'Bondowoso',        'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-7.9070,  'lng'=>113.8230],
            ['name'=>'Gresik',           'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-7.1560,  'lng'=>112.6550],
            ['name'=>'Jember',           'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-8.1845,  'lng'=>113.6714],
            ['name'=>'Jombang',          'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-7.5460,  'lng'=>112.2240],
            ['name'=>'Kediri',           'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-7.8080,  'lng'=>112.0180],
            ['name'=>'Lamongan',         'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-7.1180,  'lng'=>112.4130],
            ['name'=>'Lumajang',         'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-8.1310,  'lng'=>113.2230],
            ['name'=>'Madiun',           'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-7.6400,  'lng'=>111.5530],
            ['name'=>'Magetan',          'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-7.6480,  'lng'=>111.3300],
            ['name'=>'Malang',           'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-8.0000,  'lng'=>112.6170],
            ['name'=>'Mojokerto',        'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-7.5520,  'lng'=>112.5330],
            ['name'=>'Nganjuk',          'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-7.6040,  'lng'=>111.9040],
            ['name'=>'Ngawi',            'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-7.4060,  'lng'=>111.4460],
            ['name'=>'Pacitan',          'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-8.1950,  'lng'=>111.1020],
            ['name'=>'Pamekasan',        'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-7.1570,  'lng'=>113.4730],
            ['name'=>'Pasuruan',         'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-7.6600,  'lng'=>112.9060],
            ['name'=>'Ponorogo',         'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-7.8650,  'lng'=>111.4630],
            ['name'=>'Probolinggo',      'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-7.7700,  'lng'=>113.1890],
            ['name'=>'Sampang',          'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-7.1950,  'lng'=>113.2440],
            ['name'=>'Sidoarjo',         'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-7.4460,  'lng'=>112.7180],
            ['name'=>'Situbondo',        'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-7.7060,  'lng'=>114.0070],
            ['name'=>'Sumenep',          'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-6.9980,  'lng'=>113.8620],
            ['name'=>'Trenggalek',       'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-8.0530,  'lng'=>111.7090],
            ['name'=>'Tuban',            'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-6.8980,  'lng'=>112.0440],
            ['name'=>'Tulungagung',      'province'=>'Jawa Timur','type'=>'Kabupaten', 'lat'=>-8.0650,  'lng'=>111.9050],

            // ── BALI ──────────────────────────────────────────────────
            ['name'=>'Denpasar',         'province'=>'Bali','type'=>'Kota',       'lat'=>-8.6705,  'lng'=>115.2126],
            ['name'=>'Badung',           'province'=>'Bali','type'=>'Kabupaten',  'lat'=>-8.5800,  'lng'=>115.1880],
            ['name'=>'Bangli',           'province'=>'Bali','type'=>'Kabupaten',  'lat'=>-8.4560,  'lng'=>115.3560],
            ['name'=>'Buleleng',         'province'=>'Bali','type'=>'Kabupaten',  'lat'=>-8.1120,  'lng'=>115.0880],
            ['name'=>'Gianyar',          'province'=>'Bali','type'=>'Kabupaten',  'lat'=>-8.5360,  'lng'=>115.3320],
            ['name'=>'Jembrana',         'province'=>'Bali','type'=>'Kabupaten',  'lat'=>-8.3630,  'lng'=>114.6240],
            ['name'=>'Karangasem',       'province'=>'Bali','type'=>'Kabupaten',  'lat'=>-8.4510,  'lng'=>115.6080],
            ['name'=>'Klungkung',        'province'=>'Bali','type'=>'Kabupaten',  'lat'=>-8.5410,  'lng'=>115.4040],
            ['name'=>'Tabanan',          'province'=>'Bali','type'=>'Kabupaten',  'lat'=>-8.5400,  'lng'=>115.1260],

            // ── NUSA TENGGARA BARAT ───────────────────────────────────
            ['name'=>'Bima',             'province'=>'NTB','type'=>'Kota',       'lat'=>-8.4608,  'lng'=>118.7265],
            ['name'=>'Mataram',          'province'=>'NTB','type'=>'Kota',       'lat'=>-8.5833,  'lng'=>116.1167],
            ['name'=>'Bima',             'province'=>'NTB','type'=>'Kabupaten',  'lat'=>-8.5350,  'lng'=>118.6870],
            ['name'=>'Dompu',            'province'=>'NTB','type'=>'Kabupaten',  'lat'=>-8.5370,  'lng'=>118.4620],
            ['name'=>'Lombok Barat',     'province'=>'NTB','type'=>'Kabupaten',  'lat'=>-8.6500,  'lng'=>116.0760],
            ['name'=>'Lombok Tengah',    'province'=>'NTB','type'=>'Kabupaten',  'lat'=>-8.7420,  'lng'=>116.2810],
            ['name'=>'Lombok Timur',     'province'=>'NTB','type'=>'Kabupaten',  'lat'=>-8.5780,  'lng'=>116.5560],
            ['name'=>'Lombok Utara',     'province'=>'NTB','type'=>'Kabupaten',  'lat'=>-8.3700,  'lng'=>116.1810],
            ['name'=>'Sumbawa',          'province'=>'NTB','type'=>'Kabupaten',  'lat'=>-8.7310,  'lng'=>117.4170],
            ['name'=>'Sumbawa Barat',    'province'=>'NTB','type'=>'Kabupaten',  'lat'=>-8.7750,  'lng'=>116.8950],

            // ── NUSA TENGGARA TIMUR ───────────────────────────────────
            ['name'=>'Kupang',           'province'=>'NTT','type'=>'Kota',       'lat'=>-10.1772, 'lng'=>123.6070],
            ['name'=>'Alor',             'province'=>'NTT','type'=>'Kabupaten',  'lat'=>-8.2240,  'lng'=>124.5130],
            ['name'=>'Belu',             'province'=>'NTT','type'=>'Kabupaten',  'lat'=>-9.5560,  'lng'=>124.8820],
            ['name'=>'Ende',             'province'=>'NTT','type'=>'Kabupaten',  'lat'=>-8.8440,  'lng'=>121.6620],
            ['name'=>'Flores Timur',     'province'=>'NTT','type'=>'Kabupaten',  'lat'=>-8.3300,  'lng'=>122.9760],
            ['name'=>'Kupang',           'province'=>'NTT','type'=>'Kabupaten',  'lat'=>-10.1600, 'lng'=>123.5540],
            ['name'=>'Lembata',          'province'=>'NTT','type'=>'Kabupaten',  'lat'=>-8.3770,  'lng'=>123.4970],
            ['name'=>'Malaka',           'province'=>'NTT','type'=>'Kabupaten',  'lat'=>-9.7820,  'lng'=>124.6390],
            ['name'=>'Manggarai',        'province'=>'NTT','type'=>'Kabupaten',  'lat'=>-8.6160,  'lng'=>120.4590],
            ['name'=>'Manggarai Barat',  'province'=>'NTT','type'=>'Kabupaten',  'lat'=>-8.4890,  'lng'=>119.8870],
            ['name'=>'Manggarai Timur',  'province'=>'NTT','type'=>'Kabupaten',  'lat'=>-8.7320,  'lng'=>120.8970],
            ['name'=>'Nagekeo',          'province'=>'NTT','type'=>'Kabupaten',  'lat'=>-8.7430,  'lng'=>121.1500],
            ['name'=>'Ngada',            'province'=>'NTT','type'=>'Kabupaten',  'lat'=>-8.6590,  'lng'=>121.0470],
            ['name'=>'Rote Ndao',        'province'=>'NTT','type'=>'Kabupaten',  'lat'=>-10.7490, 'lng'=>123.0690],
            ['name'=>'Sabu Raijua',      'province'=>'NTT','type'=>'Kabupaten',  'lat'=>-10.4860, 'lng'=>121.8560],
            ['name'=>'Sikka',            'province'=>'NTT','type'=>'Kabupaten',  'lat'=>-8.5910,  'lng'=>122.2120],
            ['name'=>'Sumba Barat',      'province'=>'NTT','type'=>'Kabupaten',  'lat'=>-9.6610,  'lng'=>119.4200],
            ['name'=>'Sumba Barat Daya', 'province'=>'NTT','type'=>'Kabupaten',  'lat'=>-9.8340,  'lng'=>119.1320],
            ['name'=>'Sumba Tengah',     'province'=>'NTT','type'=>'Kabupaten',  'lat'=>-9.6500,  'lng'=>119.9250],
            ['name'=>'Sumba Timur',      'province'=>'NTT','type'=>'Kabupaten',  'lat'=>-9.6590,  'lng'=>120.2630],
            ['name'=>'Timor Tengah Selatan','province'=>'NTT','type'=>'Kabupaten','lat'=>-9.7330, 'lng'=>124.1990],
            ['name'=>'Timor Tengah Utara','province'=>'NTT','type'=>'Kabupaten', 'lat'=>-9.3660,  'lng'=>124.4610],

            // ── KALIMANTAN BARAT ──────────────────────────────────────
            ['name'=>'Pontianak',        'province'=>'Kalimantan Barat','type'=>'Kota',      'lat'=>-0.0263, 'lng'=>109.3425],
            ['name'=>'Singkawang',       'province'=>'Kalimantan Barat','type'=>'Kota',      'lat'=>0.9078,  'lng'=>108.9757],
            ['name'=>'Bengkayang',       'province'=>'Kalimantan Barat','type'=>'Kabupaten', 'lat'=>0.8080,  'lng'=>109.2830],
            ['name'=>'Kapuas Hulu',      'province'=>'Kalimantan Barat','type'=>'Kabupaten', 'lat'=>0.7910,  'lng'=>113.2100],
            ['name'=>'Kayong Utara',     'province'=>'Kalimantan Barat','type'=>'Kabupaten', 'lat'=>-1.2360, 'lng'=>110.0070],
            ['name'=>'Ketapang',         'province'=>'Kalimantan Barat','type'=>'Kabupaten', 'lat'=>-1.8360, 'lng'=>110.0170],
            ['name'=>'Kubu Raya',        'province'=>'Kalimantan Barat','type'=>'Kabupaten', 'lat'=>-0.2140, 'lng'=>109.2970],
            ['name'=>'Landak',           'province'=>'Kalimantan Barat','type'=>'Kabupaten', 'lat'=>0.3960,  'lng'=>109.9610],
            ['name'=>'Melawi',           'province'=>'Kalimantan Barat','type'=>'Kabupaten', 'lat'=>-0.4170, 'lng'=>111.4740],
            ['name'=>'Mempawah',         'province'=>'Kalimantan Barat','type'=>'Kabupaten', 'lat'=>0.3760,  'lng'=>108.9990],
            ['name'=>'Sambas',           'province'=>'Kalimantan Barat','type'=>'Kabupaten', 'lat'=>1.3580,  'lng'=>109.2990],
            ['name'=>'Sanggau',          'province'=>'Kalimantan Barat','type'=>'Kabupaten', 'lat'=>0.1290,  'lng'=>110.5820],
            ['name'=>'Sekadau',          'province'=>'Kalimantan Barat','type'=>'Kabupaten', 'lat'=>0.0280,  'lng'=>110.9560],
            ['name'=>'Sintang',          'province'=>'Kalimantan Barat','type'=>'Kabupaten', 'lat'=>0.0640,  'lng'=>111.4730],

            // ── KALIMANTAN TENGAH ─────────────────────────────────────
            ['name'=>'Palangkaraya',     'province'=>'Kalimantan Tengah','type'=>'Kota',      'lat'=>-2.2161, 'lng'=>113.9135],
            ['name'=>'Barito Selatan',   'province'=>'Kalimantan Tengah','type'=>'Kabupaten', 'lat'=>-1.8630, 'lng'=>114.7710],
            ['name'=>'Barito Timur',     'province'=>'Kalimantan Tengah','type'=>'Kabupaten', 'lat'=>-1.5820, 'lng'=>115.3200],
            ['name'=>'Barito Utara',     'province'=>'Kalimantan Tengah','type'=>'Kabupaten', 'lat'=>-0.8970, 'lng'=>114.7850],
            ['name'=>'Gunung Mas',       'province'=>'Kalimantan Tengah','type'=>'Kabupaten', 'lat'=>-1.5830, 'lng'=>113.7050],
            ['name'=>'Kapuas',           'province'=>'Kalimantan Tengah','type'=>'Kabupaten', 'lat'=>-2.0110, 'lng'=>114.3520],
            ['name'=>'Katingan',         'province'=>'Kalimantan Tengah','type'=>'Kabupaten', 'lat'=>-1.8080, 'lng'=>113.1070],
            ['name'=>'Kotawaringin Barat','province'=>'Kalimantan Tengah','type'=>'Kabupaten','lat'=>-2.6400,'lng'=>111.6880],
            ['name'=>'Kotawaringin Timur','province'=>'Kalimantan Tengah','type'=>'Kabupaten','lat'=>-1.8390,'lng'=>112.9850],
            ['name'=>'Lamandau',         'province'=>'Kalimantan Tengah','type'=>'Kabupaten', 'lat'=>-2.4010, 'lng'=>111.3780],
            ['name'=>'Murung Raya',      'province'=>'Kalimantan Tengah','type'=>'Kabupaten', 'lat'=>-0.4870, 'lng'=>114.6210],
            ['name'=>'Pulang Pisau',     'province'=>'Kalimantan Tengah','type'=>'Kabupaten', 'lat'=>-2.4580, 'lng'=>114.1010],
            ['name'=>'Seruyan',          'province'=>'Kalimantan Tengah','type'=>'Kabupaten', 'lat'=>-2.4690, 'lng'=>112.4090],
            ['name'=>'Sukamara',         'province'=>'Kalimantan Tengah','type'=>'Kabupaten', 'lat'=>-2.6720, 'lng'=>111.1550],

            // ── KALIMANTAN SELATAN ────────────────────────────────────
            ['name'=>'Banjarbaru',       'province'=>'Kalimantan Selatan','type'=>'Kota',      'lat'=>-3.4423, 'lng'=>114.8266],
            ['name'=>'Banjarmasin',      'province'=>'Kalimantan Selatan','type'=>'Kota',      'lat'=>-3.3194, 'lng'=>114.5908],
            ['name'=>'Balangan',         'province'=>'Kalimantan Selatan','type'=>'Kabupaten', 'lat'=>-2.3850, 'lng'=>115.4230],
            ['name'=>'Banjar',           'province'=>'Kalimantan Selatan','type'=>'Kabupaten', 'lat'=>-3.5820, 'lng'=>114.9720],
            ['name'=>'Barito Kuala',     'province'=>'Kalimantan Selatan','type'=>'Kabupaten', 'lat'=>-3.0200, 'lng'=>114.5320],
            ['name'=>'Hulu Sungai Selatan','province'=>'Kalimantan Selatan','type'=>'Kabupaten','lat'=>-2.5610,'lng'=>115.2000],
            ['name'=>'Hulu Sungai Tengah','province'=>'Kalimantan Selatan','type'=>'Kabupaten','lat'=>-2.3460,'lng'=>115.3720],
            ['name'=>'Hulu Sungai Utara','province'=>'Kalimantan Selatan','type'=>'Kabupaten', 'lat'=>-2.1270, 'lng'=>115.2430],
            ['name'=>'Kotabaru',         'province'=>'Kalimantan Selatan','type'=>'Kabupaten', 'lat'=>-3.2940, 'lng'=>116.2220],
            ['name'=>'Tabalong',         'province'=>'Kalimantan Selatan','type'=>'Kabupaten', 'lat'=>-2.0460, 'lng'=>115.4200],
            ['name'=>'Tanah Bumbu',      'province'=>'Kalimantan Selatan','type'=>'Kabupaten', 'lat'=>-3.4880, 'lng'=>115.7680],
            ['name'=>'Tanah Laut',       'province'=>'Kalimantan Selatan','type'=>'Kabupaten', 'lat'=>-3.7920, 'lng'=>115.0150],
            ['name'=>'Tapin',            'province'=>'Kalimantan Selatan','type'=>'Kabupaten', 'lat'=>-3.0310, 'lng'=>115.0090],

            // ── KALIMANTAN TIMUR ──────────────────────────────────────
            ['name'=>'Balikpapan',       'province'=>'Kalimantan Timur','type'=>'Kota',      'lat'=>-1.2379,  'lng'=>116.8529],
            ['name'=>'Bontang',          'province'=>'Kalimantan Timur','type'=>'Kota',      'lat'=>0.1338,   'lng'=>117.4993],
            ['name'=>'Samarinda',        'province'=>'Kalimantan Timur','type'=>'Kota',      'lat'=>-0.5022,  'lng'=>117.1536],
            ['name'=>'Berau',            'province'=>'Kalimantan Timur','type'=>'Kabupaten', 'lat'=>2.1460,   'lng'=>117.4290],
            ['name'=>'Kutai Barat',      'province'=>'Kalimantan Timur','type'=>'Kabupaten', 'lat'=>-0.5290,  'lng'=>115.6220],
            ['name'=>'Kutai Kartanegara','province'=>'Kalimantan Timur','type'=>'Kabupaten', 'lat'=>-0.4520,  'lng'=>116.9800],
            ['name'=>'Kutai Timur',      'province'=>'Kalimantan Timur','type'=>'Kabupaten', 'lat'=>1.4410,   'lng'=>117.6770],
            ['name'=>'Mahakam Ulu',      'province'=>'Kalimantan Timur','type'=>'Kabupaten', 'lat'=>0.6820,   'lng'=>115.5760],
            ['name'=>'Paser',            'province'=>'Kalimantan Timur','type'=>'Kabupaten', 'lat'=>-1.8360,  'lng'=>116.2240],
            ['name'=>'Penajam Paser Utara','province'=>'Kalimantan Timur','type'=>'Kabupaten','lat'=>-1.2620, 'lng'=>116.5820],

            // ── KALIMANTAN UTARA ──────────────────────────────────────
            ['name'=>'Tarakan',          'province'=>'Kalimantan Utara','type'=>'Kota',      'lat'=>3.3017,   'lng'=>117.6356],
            ['name'=>'Bulungan',         'province'=>'Kalimantan Utara','type'=>'Kabupaten', 'lat'=>2.8990,   'lng'=>117.3980],
            ['name'=>'Malinau',          'province'=>'Kalimantan Utara','type'=>'Kabupaten', 'lat'=>3.5850,   'lng'=>116.6310],
            ['name'=>'Nunukan',          'province'=>'Kalimantan Utara','type'=>'Kabupaten', 'lat'=>4.1350,   'lng'=>117.6680],
            ['name'=>'Tana Tidung',      'province'=>'Kalimantan Utara','type'=>'Kabupaten', 'lat'=>3.8260,   'lng'=>117.2540],

            // ── SULAWESI UTARA ────────────────────────────────────────
            ['name'=>'Bitung',           'province'=>'Sulawesi Utara','type'=>'Kota',      'lat'=>1.4390,   'lng'=>125.1980],
            ['name'=>'Kotamobagu',       'province'=>'Sulawesi Utara','type'=>'Kota',      'lat'=>0.7280,   'lng'=>124.3070],
            ['name'=>'Manado',           'province'=>'Sulawesi Utara','type'=>'Kota',      'lat'=>1.4748,   'lng'=>124.8421],
            ['name'=>'Tomohon',          'province'=>'Sulawesi Utara','type'=>'Kota',      'lat'=>1.3228,   'lng'=>124.8297],
            ['name'=>'Bolaang Mongondow','province'=>'Sulawesi Utara','type'=>'Kabupaten', 'lat'=>0.5940,   'lng'=>124.0050],
            ['name'=>'Bolaang Mongondow Selatan','province'=>'Sulawesi Utara','type'=>'Kabupaten','lat'=>0.3180,'lng'=>124.2860],
            ['name'=>'Bolaang Mongondow Timur','province'=>'Sulawesi Utara','type'=>'Kabupaten','lat'=>0.7690,'lng'=>124.5870],
            ['name'=>'Bolaang Mongondow Utara','province'=>'Sulawesi Utara','type'=>'Kabupaten','lat'=>1.0980,'lng'=>124.0680],
            ['name'=>'Kepulauan Sangihe','province'=>'Sulawesi Utara','type'=>'Kabupaten', 'lat'=>3.5730,   'lng'=>125.5560],
            ['name'=>'Kepulauan Siau Tagulandang Biaro','province'=>'Sulawesi Utara','type'=>'Kabupaten','lat'=>2.7260,'lng'=>125.3880],
            ['name'=>'Kepulauan Talaud', 'province'=>'Sulawesi Utara','type'=>'Kabupaten', 'lat'=>4.3700,   'lng'=>126.8060],
            ['name'=>'Minahasa',         'province'=>'Sulawesi Utara','type'=>'Kabupaten', 'lat'=>1.2320,   'lng'=>124.8320],
            ['name'=>'Minahasa Selatan', 'province'=>'Sulawesi Utara','type'=>'Kabupaten', 'lat'=>1.0180,   'lng'=>124.5780],
            ['name'=>'Minahasa Tenggara','province'=>'Sulawesi Utara','type'=>'Kabupaten', 'lat'=>0.8280,   'lng'=>124.8760],
            ['name'=>'Minahasa Utara',   'province'=>'Sulawesi Utara','type'=>'Kabupaten', 'lat'=>1.5780,   'lng'=>125.0380],

            // ── GORONTALO ─────────────────────────────────────────────
            ['name'=>'Gorontalo',        'province'=>'Gorontalo','type'=>'Kota',       'lat'=>0.5412,   'lng'=>123.0595],
            ['name'=>'Boalemo',          'province'=>'Gorontalo','type'=>'Kabupaten',  'lat'=>0.4380,   'lng'=>122.3250],
            ['name'=>'Bone Bolango',     'province'=>'Gorontalo','type'=>'Kabupaten',  'lat'=>0.6310,   'lng'=>123.2240],
            ['name'=>'Gorontalo',        'province'=>'Gorontalo','type'=>'Kabupaten',  'lat'=>0.5160,   'lng'=>122.8420],
            ['name'=>'Gorontalo Utara',  'province'=>'Gorontalo','type'=>'Kabupaten',  'lat'=>0.8930,   'lng'=>122.7340],
            ['name'=>'Pohuwato',         'province'=>'Gorontalo','type'=>'Kabupaten',  'lat'=>0.3430,   'lng'=>121.8700],

            // ── SULAWESI TENGAH ───────────────────────────────────────
            ['name'=>'Palu',             'province'=>'Sulawesi Tengah','type'=>'Kota',      'lat'=>-0.9003, 'lng'=>119.8779],
            ['name'=>'Banggai',          'province'=>'Sulawesi Tengah','type'=>'Kabupaten', 'lat'=>-1.5380, 'lng'=>123.4860],
            ['name'=>'Banggai Kepulauan','province'=>'Sulawesi Tengah','type'=>'Kabupaten', 'lat'=>-1.7280, 'lng'=>123.5070],
            ['name'=>'Banggai Laut',     'province'=>'Sulawesi Tengah','type'=>'Kabupaten', 'lat'=>-1.6430, 'lng'=>123.4870],
            ['name'=>'Buol',             'province'=>'Sulawesi Tengah','type'=>'Kabupaten', 'lat'=>1.2100,  'lng'=>121.4430],
            ['name'=>'Donggala',         'province'=>'Sulawesi Tengah','type'=>'Kabupaten', 'lat'=>-0.5320, 'lng'=>119.7420],
            ['name'=>'Morowali',         'province'=>'Sulawesi Tengah','type'=>'Kabupaten', 'lat'=>-2.3340, 'lng'=>121.9430],
            ['name'=>'Morowali Utara',   'province'=>'Sulawesi Tengah','type'=>'Kabupaten', 'lat'=>-1.6210, 'lng'=>121.6060],
            ['name'=>'Parigi Moutong',   'province'=>'Sulawesi Tengah','type'=>'Kabupaten', 'lat'=>-0.6390, 'lng'=>120.2650],
            ['name'=>'Poso',             'province'=>'Sulawesi Tengah','type'=>'Kabupaten', 'lat'=>-1.3910, 'lng'=>120.7510],
            ['name'=>'Sigi',             'province'=>'Sulawesi Tengah','type'=>'Kabupaten', 'lat'=>-1.1640, 'lng'=>119.8650],
            ['name'=>'Tojo Una-Una',     'province'=>'Sulawesi Tengah','type'=>'Kabupaten', 'lat'=>-0.6440, 'lng'=>121.5820],
            ['name'=>'Tolitoli',         'province'=>'Sulawesi Tengah','type'=>'Kabupaten', 'lat'=>1.0310,  'lng'=>120.7940],

            // ── SULAWESI SELATAN ──────────────────────────────────────
            ['name'=>'Makassar',         'province'=>'Sulawesi Selatan','type'=>'Kota',      'lat'=>-5.1477, 'lng'=>119.4327],
            ['name'=>'Palopo',           'province'=>'Sulawesi Selatan','type'=>'Kota',      'lat'=>-2.9926, 'lng'=>120.1964],
            ['name'=>'Parepare',         'province'=>'Sulawesi Selatan','type'=>'Kota',      'lat'=>-4.0135, 'lng'=>119.6286],
            ['name'=>'Bantaeng',         'province'=>'Sulawesi Selatan','type'=>'Kabupaten', 'lat'=>-5.5320, 'lng'=>119.9650],
            ['name'=>'Barru',            'province'=>'Sulawesi Selatan','type'=>'Kabupaten', 'lat'=>-4.4080, 'lng'=>119.6200],
            ['name'=>'Bone',             'province'=>'Sulawesi Selatan','type'=>'Kabupaten', 'lat'=>-4.5450, 'lng'=>120.3270],
            ['name'=>'Bulukumba',        'province'=>'Sulawesi Selatan','type'=>'Kabupaten', 'lat'=>-5.5540, 'lng'=>120.1990],
            ['name'=>'Enrekang',         'province'=>'Sulawesi Selatan','type'=>'Kabupaten', 'lat'=>-3.5680, 'lng'=>119.7870],
            ['name'=>'Gowa',             'province'=>'Sulawesi Selatan','type'=>'Kabupaten', 'lat'=>-5.2920, 'lng'=>119.6890],
            ['name'=>'Jeneponto',        'province'=>'Sulawesi Selatan','type'=>'Kabupaten', 'lat'=>-5.6680, 'lng'=>119.7450],
            ['name'=>'Kepulauan Selayar','province'=>'Sulawesi Selatan','type'=>'Kabupaten', 'lat'=>-6.1270, 'lng'=>120.4500],
            ['name'=>'Luwu',             'province'=>'Sulawesi Selatan','type'=>'Kabupaten', 'lat'=>-3.0370, 'lng'=>120.5490],
            ['name'=>'Luwu Timur',       'province'=>'Sulawesi Selatan','type'=>'Kabupaten', 'lat'=>-2.5510, 'lng'=>121.4220],
            ['name'=>'Luwu Utara',       'province'=>'Sulawesi Selatan','type'=>'Kabupaten', 'lat'=>-2.5760, 'lng'=>120.4870],
            ['name'=>'Maros',            'province'=>'Sulawesi Selatan','type'=>'Kabupaten', 'lat'=>-4.9820, 'lng'=>119.5840],
            ['name'=>'Pangkajene Kepulauan','province'=>'Sulawesi Selatan','type'=>'Kabupaten','lat'=>-4.8310,'lng'=>119.5290],
            ['name'=>'Pinrang',          'province'=>'Sulawesi Selatan','type'=>'Kabupaten', 'lat'=>-3.7870, 'lng'=>119.6520],
            ['name'=>'Sidenreng Rappang','province'=>'Sulawesi Selatan','type'=>'Kabupaten', 'lat'=>-3.9280, 'lng'=>119.7980],
            ['name'=>'Sinjai',           'province'=>'Sulawesi Selatan','type'=>'Kabupaten', 'lat'=>-5.1240, 'lng'=>120.2510],
            ['name'=>'Soppeng',          'province'=>'Sulawesi Selatan','type'=>'Kabupaten', 'lat'=>-4.3440, 'lng'=>119.8940],
            ['name'=>'Takalar',          'province'=>'Sulawesi Selatan','type'=>'Kabupaten', 'lat'=>-5.4290, 'lng'=>119.4540],
            ['name'=>'Tana Toraja',      'province'=>'Sulawesi Selatan','type'=>'Kabupaten', 'lat'=>-3.0470, 'lng'=>119.8240],
            ['name'=>'Toraja Utara',     'province'=>'Sulawesi Selatan','type'=>'Kabupaten', 'lat'=>-2.9700, 'lng'=>119.9110],
            ['name'=>'Wajo',             'province'=>'Sulawesi Selatan','type'=>'Kabupaten', 'lat'=>-3.9910, 'lng'=>120.2810],

            // ── SULAWESI TENGGARA ─────────────────────────────────────
            ['name'=>'Bau-Bau',          'province'=>'Sulawesi Tenggara','type'=>'Kota',      'lat'=>-5.4766, 'lng'=>122.6274],
            ['name'=>'Kendari',          'province'=>'Sulawesi Tenggara','type'=>'Kota',      'lat'=>-3.9985, 'lng'=>122.5129],
            ['name'=>'Bombana',          'province'=>'Sulawesi Tenggara','type'=>'Kabupaten', 'lat'=>-4.7720, 'lng'=>121.7770],
            ['name'=>'Buton',            'province'=>'Sulawesi Tenggara','type'=>'Kabupaten', 'lat'=>-5.2460, 'lng'=>122.6240],
            ['name'=>'Buton Selatan',    'province'=>'Sulawesi Tenggara','type'=>'Kabupaten', 'lat'=>-5.5120, 'lng'=>122.5980],
            ['name'=>'Buton Tengah',     'province'=>'Sulawesi Tenggara','type'=>'Kabupaten', 'lat'=>-4.9940, 'lng'=>122.5080],
            ['name'=>'Buton Utara',      'province'=>'Sulawesi Tenggara','type'=>'Kabupaten', 'lat'=>-4.5120, 'lng'=>122.7520],
            ['name'=>'Kolaka',           'province'=>'Sulawesi Tenggara','type'=>'Kabupaten', 'lat'=>-4.0530, 'lng'=>121.5740],
            ['name'=>'Kolaka Timur',     'province'=>'Sulawesi Tenggara','type'=>'Kabupaten', 'lat'=>-4.0830, 'lng'=>121.7980],
            ['name'=>'Kolaka Utara',     'province'=>'Sulawesi Tenggara','type'=>'Kabupaten', 'lat'=>-3.4450, 'lng'=>121.5810],
            ['name'=>'Konawe',           'province'=>'Sulawesi Tenggara','type'=>'Kabupaten', 'lat'=>-3.9120, 'lng'=>122.4890],
            ['name'=>'Konawe Kepulauan','province'=>'Sulawesi Tenggara','type'=>'Kabupaten',  'lat'=>-3.8730, 'lng'=>122.8750],
            ['name'=>'Konawe Selatan',   'province'=>'Sulawesi Tenggara','type'=>'Kabupaten', 'lat'=>-4.4310, 'lng'=>122.4720],
            ['name'=>'Konawe Utara',     'province'=>'Sulawesi Tenggara','type'=>'Kabupaten', 'lat'=>-3.2960, 'lng'=>122.1250],
            ['name'=>'Muna',             'province'=>'Sulawesi Tenggara','type'=>'Kabupaten', 'lat'=>-4.8940, 'lng'=>122.5450],
            ['name'=>'Muna Barat',       'province'=>'Sulawesi Tenggara','type'=>'Kabupaten', 'lat'=>-4.7980, 'lng'=>122.3400],
            ['name'=>'Wakatobi',         'province'=>'Sulawesi Tenggara','type'=>'Kabupaten', 'lat'=>-5.4900, 'lng'=>123.5870],

            // ── MALUKU ────────────────────────────────────────────────
            ['name'=>'Ambon',            'province'=>'Maluku','type'=>'Kota',       'lat'=>-3.6954,  'lng'=>128.1814],
            ['name'=>'Tual',             'province'=>'Maluku','type'=>'Kota',       'lat'=>-5.6358,  'lng'=>132.7511],
            ['name'=>'Buru',             'province'=>'Maluku','type'=>'Kabupaten',  'lat'=>-3.3990,  'lng'=>126.7290],
            ['name'=>'Buru Selatan',     'province'=>'Maluku','type'=>'Kabupaten',  'lat'=>-3.9650,  'lng'=>126.6490],
            ['name'=>'Kepulauan Aru',    'province'=>'Maluku','type'=>'Kabupaten',  'lat'=>-6.2060,  'lng'=>134.5390],
            ['name'=>'Maluku Barat Daya','province'=>'Maluku','type'=>'Kabupaten',  'lat'=>-7.5900,  'lng'=>128.1680],
            ['name'=>'Maluku Tengah',    'province'=>'Maluku','type'=>'Kabupaten',  'lat'=>-3.3410,  'lng'=>129.1290],
            ['name'=>'Maluku Tenggara',  'province'=>'Maluku','type'=>'Kabupaten',  'lat'=>-5.6360,  'lng'=>132.7470],
            ['name'=>'Maluku Tenggara Barat','province'=>'Maluku','type'=>'Kabupaten','lat'=>-7.9700,'lng'=>131.3000],
            ['name'=>'Seram Bagian Barat','province'=>'Maluku','type'=>'Kabupaten', 'lat'=>-3.0800,  'lng'=>128.1960],
            ['name'=>'Seram Bagian Timur','province'=>'Maluku','type'=>'Kabupaten', 'lat'=>-3.2320,  'lng'=>130.8420],

            // ── MALUKU UTARA ──────────────────────────────────────────
            ['name'=>'Ternate',          'province'=>'Maluku Utara','type'=>'Kota',      'lat'=>0.7833,   'lng'=>127.3667],
            ['name'=>'Tidore Kepulauan','province'=>'Maluku Utara','type'=>'Kota',       'lat'=>0.6780,   'lng'=>127.4350],
            ['name'=>'Halmahera Barat',  'province'=>'Maluku Utara','type'=>'Kabupaten', 'lat'=>1.0790,   'lng'=>127.5090],
            ['name'=>'Halmahera Selatan','province'=>'Maluku Utara','type'=>'Kabupaten', 'lat'=>-0.5990,  'lng'=>127.9840],
            ['name'=>'Halmahera Tengah', 'province'=>'Maluku Utara','type'=>'Kabupaten', 'lat'=>0.6620,   'lng'=>128.1580],
            ['name'=>'Halmahera Timur',  'province'=>'Maluku Utara','type'=>'Kabupaten', 'lat'=>0.9950,   'lng'=>128.4130],
            ['name'=>'Halmahera Utara',  'province'=>'Maluku Utara','type'=>'Kabupaten', 'lat'=>1.7880,   'lng'=>127.9900],
            ['name'=>'Kepulauan Sula',   'province'=>'Maluku Utara','type'=>'Kabupaten', 'lat'=>-1.8870,  'lng'=>125.3830],
            ['name'=>'Pulau Morotai',    'province'=>'Maluku Utara','type'=>'Kabupaten', 'lat'=>2.3640,   'lng'=>128.3320],
            ['name'=>'Pulau Taliabu',    'province'=>'Maluku Utara','type'=>'Kabupaten', 'lat'=>-1.7930,  'lng'=>124.7450],

            // ── PAPUA BARAT ───────────────────────────────────────────
            ['name'=>'Sorong',           'province'=>'Papua Barat','type'=>'Kota',      'lat'=>-0.8762,  'lng'=>131.2559],
            ['name'=>'Fakfak',           'province'=>'Papua Barat','type'=>'Kabupaten', 'lat'=>-2.9220,  'lng'=>132.3020],
            ['name'=>'Kaimana',          'province'=>'Papua Barat','type'=>'Kabupaten', 'lat'=>-3.6440,  'lng'=>133.7420],
            ['name'=>'Manokwari',        'province'=>'Papua Barat','type'=>'Kabupaten', 'lat'=>-0.8615,  'lng'=>134.0622],
            ['name'=>'Manokwari Selatan','province'=>'Papua Barat','type'=>'Kabupaten', 'lat'=>-1.4790,  'lng'=>133.9210],
            ['name'=>'Maybrat',          'province'=>'Papua Barat','type'=>'Kabupaten', 'lat'=>-1.4230,  'lng'=>132.3360],
            ['name'=>'Pegunungan Arfak', 'province'=>'Papua Barat','type'=>'Kabupaten', 'lat'=>-1.2600,  'lng'=>133.8380],
            ['name'=>'Raja Ampat',       'province'=>'Papua Barat','type'=>'Kabupaten', 'lat'=>-0.4380,  'lng'=>130.7880],
            ['name'=>'Sorong',           'province'=>'Papua Barat','type'=>'Kabupaten', 'lat'=>-1.1060,  'lng'=>131.4870],
            ['name'=>'Sorong Selatan',   'province'=>'Papua Barat','type'=>'Kabupaten', 'lat'=>-1.8740,  'lng'=>132.0860],
            ['name'=>'Tambrauw',         'province'=>'Papua Barat','type'=>'Kabupaten', 'lat'=>-0.9670,  'lng'=>132.6850],
            ['name'=>'Teluk Bintuni',    'province'=>'Papua Barat','type'=>'Kabupaten', 'lat'=>-2.1140,  'lng'=>133.5260],
            ['name'=>'Teluk Wondama',    'province'=>'Papua Barat','type'=>'Kabupaten', 'lat'=>-2.4550,  'lng'=>134.3350],

            // ── PAPUA ─────────────────────────────────────────────────
            ['name'=>'Jayapura',         'province'=>'Papua','type'=>'Kota',       'lat'=>-2.5337,  'lng'=>140.7181],
            ['name'=>'Asmat',            'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-5.7440,  'lng'=>138.4490],
            ['name'=>'Biak Numfor',      'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-0.9780,  'lng'=>135.8260],
            ['name'=>'Boven Digoel',     'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-5.7610,  'lng'=>140.2830],
            ['name'=>'Deiyai',           'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-3.9240,  'lng'=>136.2670],
            ['name'=>'Dogiyai',          'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-3.9870,  'lng'=>136.2170],
            ['name'=>'Intan Jaya',       'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-3.6400,  'lng'=>136.3050],
            ['name'=>'Jayapura',         'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-2.7130,  'lng'=>140.4020],
            ['name'=>'Jayawijaya',       'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-3.9030,  'lng'=>138.9000],
            ['name'=>'Keerom',           'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-3.2980,  'lng'=>140.6360],
            ['name'=>'Kepulauan Yapen',  'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-1.7840,  'lng'=>136.2310],
            ['name'=>'Lanny Jaya',       'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-3.8590,  'lng'=>138.0970],
            ['name'=>'Mamberamo Raya',   'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-2.0250,  'lng'=>138.2850],
            ['name'=>'Mamberamo Tengah', 'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-3.5480,  'lng'=>138.3560],
            ['name'=>'Mappi',            'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-6.3420,  'lng'=>139.3220],
            ['name'=>'Merauke',          'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-8.4942,  'lng'=>140.4017],
            ['name'=>'Mimika',           'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-4.5272,  'lng'=>136.8876],
            ['name'=>'Nabire',           'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-3.3780,  'lng'=>135.5000],
            ['name'=>'Nduga',            'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-4.6140,  'lng'=>138.4700],
            ['name'=>'Paniai',           'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-3.9920,  'lng'=>136.2600],
            ['name'=>'Pegunungan Bintang','province'=>'Papua','type'=>'Kabupaten', 'lat'=>-4.9630,  'lng'=>140.3090],
            ['name'=>'Puncak',           'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-3.7560,  'lng'=>137.1510],
            ['name'=>'Puncak Jaya',      'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-3.5370,  'lng'=>137.2280],
            ['name'=>'Sarmi',            'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-1.8620,  'lng'=>138.7540],
            ['name'=>'Supiori',          'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-0.6780,  'lng'=>135.6030],
            ['name'=>'Tolikara',         'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-3.7620,  'lng'=>138.4660],
            ['name'=>'Waropen',          'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-2.7520,  'lng'=>136.4490],
            ['name'=>'Yahukimo',         'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-4.5490,  'lng'=>139.4140],
            ['name'=>'Yalimo',           'province'=>'Papua','type'=>'Kabupaten',  'lat'=>-3.9810,  'lng'=>139.2060],
        ];
    }
};